import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from "docx";
import type { HimalayaResultsViewModel, AssetGroup } from "./types";

function heading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel] = HeadingLevel.HEADING_2) {
  return new Paragraph({ heading: level, spacing: { before: 300, after: 100 }, children: [new TextRun({ text, bold: true })] });
}

function body(text: string) {
  return new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text, size: 22 })] });
}

function bullet(text: string) {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 40 },
    children: [new TextRun({ text, size: 22 })],
  });
}

function separator() {
  return new Paragraph({
    spacing: { before: 200, after: 200 },
    border: {
      bottom: { color: "CCCCCC", space: 1, style: BorderStyle.SINGLE, size: 6 },
    },
  });
}

function assetGroupToParagraphs(group: AssetGroup): Paragraph[] {
  const paras: Paragraph[] = [heading(group.title, HeadingLevel.HEADING_3)];

  if (group.type === "text") {
    paras.push(body(group.content as string));
  } else if (group.type === "list") {
    for (const item of group.content as string[]) {
      paras.push(bullet(item));
    }
  } else if (group.type === "kv") {
    for (const { label, value } of group.content as { label: string; value: string }[]) {
      paras.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: `${label}: `, bold: true, size: 22 }),
            new TextRun({ text: value, size: 22 }),
          ],
        })
      );
    }
  } else if (group.type === "scripts") {
    for (const script of group.content as { title: string; duration: string; sections: { timestamp: string; direction: string; copy: string }[] }[]) {
      paras.push(
        new Paragraph({
          spacing: { before: 100, after: 60 },
          children: [
            new TextRun({ text: `${script.title} (${script.duration})`, bold: true, size: 22 }),
          ],
        })
      );
      for (const sec of script.sections) {
        paras.push(
          new Paragraph({
            spacing: { after: 40 },
            children: [
              new TextRun({ text: `[${sec.timestamp}] `, bold: true, size: 20, color: "666666" }),
              new TextRun({ text: sec.direction, italics: true, size: 20, color: "888888" }),
            ],
          })
        );
        paras.push(body(`"${sec.copy}"`));
      }
    }
  }

  return paras;
}

export async function generateDocx(vm: HimalayaResultsViewModel): Promise<Blob> {
  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.LEFT,
      spacing: { after: 100 },
      children: [new TextRun({ text: vm.title, bold: true })],
    })
  );

  // Meta
  children.push(
    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({ text: `${vm.modeLabel} · Score: ${vm.score}/100 · ${vm.statusLabel}`, size: 20, color: "888888" }),
      ],
    })
  );

  // Summary
  children.push(heading("Summary"));
  children.push(body(vm.summary));

  // Priorities
  if (vm.priorities.length > 0) {
    children.push(separator());
    children.push(heading("Top Priorities"));
    for (const p of vm.priorities) {
      children.push(
        new Paragraph({
          spacing: { after: 40 },
          children: [new TextRun({ text: p.label, bold: true, size: 22 })],
        })
      );
      children.push(body(`Why: ${p.reason}`));
      children.push(body(`Next: ${p.nextStep}`));
    }
  }

  // Assets
  if (vm.assetGroups.length > 0) {
    children.push(separator());
    children.push(heading("Generated Assets"));
    for (const group of vm.assetGroups) {
      children.push(...assetGroupToParagraphs(group));
    }
  }

  // Notes
  if (vm.notes.length > 0) {
    children.push(separator());
    children.push(heading("Notes"));
    for (const n of vm.notes) {
      children.push(bullet(n));
    }
  }

  // Footer
  children.push(separator());
  children.push(
    new Paragraph({
      spacing: { before: 100 },
      children: [
        new TextRun({ text: `Run ID: ${vm.analysisId} · Generated by Himalaya`, size: 18, color: "AAAAAA" }),
      ],
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  return Packer.toBlob(doc);
}
