// ---------------------------------------------------------------------------
// GET /api/exports/report?runId=xxx
// Generates a printable HTML report for a Himalaya analysis run
// Open in browser → Print → PDF
// ---------------------------------------------------------------------------

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";
import { getOrCreateUser } from "@/lib/auth";
import { generatePrintableHtml } from "@/lib/exports/pdfExport";

export async function GET(req: NextRequest) {
  try {
    const { userId: clerkId } = await auth();
    if (!clerkId) return new NextResponse("Unauthorized", { status: 401 });
    const user = await getOrCreateUser();
    if (!user) return new NextResponse("Unauthorized", { status: 401 });

    const runId = req.nextUrl.searchParams.get("runId");
    if (!runId) return new NextResponse("runId required", { status: 400 });

    const run = await prisma.analysisRun.findFirst({
      where: { id: runId, userId: user.id },
      include: { assetPackages: true },
    });

    if (!run) return new NextResponse("Not found", { status: 404 });

    const packet = run.decisionPacket as Record<string, unknown> | null;
    const assets = run.assetPackages[0];

    const sections: { heading: string; content: string }[] = [];

    // Summary
    sections.push({
      heading: "Executive Summary",
      content: [
        `**Score:** ${run.score ?? "—"}/100`,
        `**Verdict:** ${run.verdict ?? "—"}`,
        `**Confidence:** ${run.confidence ?? "—"}`,
        "",
        run.summary ?? "",
      ].join("\n"),
    });

    // Analysis
    if (packet) {
      sections.push({
        heading: "Analysis",
        content: [
          `**Audience:** ${packet.audience ?? "—"}`,
          `**Pain/Desire:** ${packet.painDesire ?? "—"}`,
          `**Angle:** ${packet.angle ?? "—"}`,
          "",
          "**Strengths:**",
          ...((packet.strengths as string[]) ?? []).map((s) => `• ${s}`),
          "",
          "**Weaknesses:**",
          ...((packet.weaknesses as string[]) ?? []).map((w) => `• ${w}`),
        ].join("\n"),
      });
    }

    // Ad Hooks
    if (assets?.adHooks) {
      const hooks = assets.adHooks as { format: string; hook: string }[];
      sections.push({
        heading: "Ad Hooks",
        content: hooks.map((h) => `**${h.format}:** "${h.hook}"`).join("\n\n"),
      });
    }

    // Landing Page
    if (assets?.landingPage) {
      const lp = assets.landingPage as Record<string, unknown>;
      sections.push({
        heading: "Landing Page Blueprint",
        content: [
          `**Headline:** ${lp.headline ?? "—"}`,
          `**Subheadline:** ${lp.subheadline ?? "—"}`,
          `**CTA:** ${lp.ctaCopy ?? "—"}`,
          "",
          "**Benefits:**",
          ...((lp.benefitBullets as string[]) ?? []).map((b) => `• ${b}`),
        ].join("\n"),
      });
    }

    const html = generatePrintableHtml({
      title: run.title ?? "Analysis Report",
      subtitle: `Generated on ${new Date().toLocaleDateString()} — Score: ${run.score ?? "—"}/100`,
      sections,
      footer: "Generated by Himalaya Marketing OS — himalaya.app",
    });

    return new NextResponse(html, {
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  } catch (err) {
    console.error("Report export error:", err);
    return new NextResponse("Failed", { status: 500 });
  }
}
