import Link from "next/link";
import { Mountain } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#020509] text-white">
      <nav className="border-b border-white/[0.04] py-4 px-6">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-cyan-500 to-purple-600 flex items-center justify-center">
            <Mountain className="w-3.5 h-3.5 text-white" />
          </div>
          <span className="text-sm font-black text-white">Himalaya</span>
        </Link>
      </nav>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 prose prose-invert prose-sm">
        <h1 className="text-2xl font-black">Terms of Service</h1>
        <p className="text-white/40">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>
        <h2>Service</h2>
        <p>Himalaya is an AI-powered business operating system. We generate websites, ads, emails, and business strategies using artificial intelligence.</p>
        <h2>Your Account</h2>
        <p>You are responsible for your account credentials and all activity under your account.</p>
        <h2>Generated Content</h2>
        <p>Content generated by Himalaya (sites, ads, emails) is yours to use commercially. You own what we build for you.</p>
        <h2>Payments</h2>
        <p>Free tier includes 2 business builds. Paid plans are billed monthly and can be canceled anytime.</p>
        <h2>Limitation of Liability</h2>
        <p>Himalaya provides tools and automation. We do not guarantee specific revenue outcomes. Results depend on execution, market conditions, and effort.</p>
        <h2>Contact</h2>
        <p>Questions? Email support@himalaya.app</p>
      </div>
    </div>
  );
}
