"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import type {
  PromptKit,
  ImagePrompt,
  VideoPrompt,
  AdCopyPrompt,
  EmailPrompt,
  LandingPrompt,
  SocialPrompt,
  OutreachPrompt,
  SeoPrompt,
} from "@/lib/himalaya/promptEngine";

// ── Types ────────────────────────────────────────────────────────────────

type PromptCategory = "images" | "videos" | "adCopy" | "emails" | "landing" | "social" | "outreach" | "seo";

type GenerationResult = {
  promptId: string;
  content: string;
  type: "text" | "image";
  imageBase64?: string;
};

type Props = {
  promptKit: PromptKit;
  businessContext: {
    title: string;
    niche: string;
    audience: string;
    painPoint: string;
    outcome: string;
  };
  campaignId: string;
  autoGenerated?: Record<string, { content: string; type: string }>;
  onVariationSaved?: () => void;
};

type ViewMode = "recommended" | "browse";

// ── Recommended picks — the highest-impact assets to auto-generate ─────

const RECOMMENDED_IDS = [
  "ad-fb-pain",        // Facebook pain hook — #1 converter
  "img-hero",          // Hero product image — needed everywhere
  "img-problem-solution", // Split image — highest-performing ad format
  "ad-tiktok-hook",    // TikTok viral hook — biggest reach platform
  "email-welcome-1",   // Welcome email — first touchpoint
  "lp-hero",           // Landing page hero — above the fold
];

// ── Category Config ─────────────────────────────────────────────────────

const CATEGORIES: { id: PromptCategory; label: string; icon: string }[] = [
  { id: "adCopy", label: "Ad Copy", icon: "✍️" },
  { id: "images", label: "Images", icon: "🖼️" },
  { id: "videos", label: "Videos", icon: "🎬" },
  { id: "emails", label: "Emails", icon: "📧" },
  { id: "landing", label: "Landing", icon: "🌐" },
  { id: "social", label: "Social", icon: "📱" },
  { id: "outreach", label: "Outreach", icon: "📨" },
  { id: "seo", label: "SEO", icon: "🔍" },
];

// ── Helpers ─────────────────────────────────────────────────────────────

type AnyPrompt = ImagePrompt | VideoPrompt | AdCopyPrompt | EmailPrompt | LandingPrompt | SocialPrompt | OutreachPrompt | SeoPrompt;

function getAllPrompts(kit: PromptKit): AnyPrompt[] {
  return [
    ...kit.adCopyPrompts,
    ...kit.imagePrompts,
    ...kit.videoPrompts,
    ...kit.emailPrompts,
    ...kit.landingPrompts,
    ...kit.socialPrompts,
    ...kit.outreachPrompts,
    ...kit.seoPrompts,
  ];
}

function getPromptsForCategory(kit: PromptKit, cat: PromptCategory): AnyPrompt[] {
  switch (cat) {
    case "images": return kit.imagePrompts;
    case "videos": return kit.videoPrompts;
    case "adCopy": return kit.adCopyPrompts;
    case "emails": return kit.emailPrompts;
    case "landing": return kit.landingPrompts;
    case "social": return kit.socialPrompts;
    case "outreach": return kit.outreachPrompts;
    case "seo": return kit.seoPrompts;
  }
}

function isImagePrompt(id: string): boolean {
  return id.startsWith("img-");
}

function getBadge(p: AnyPrompt): string | undefined {
  return (p as { platform?: string }).platform
    || (p as { format?: string }).format
    || (p as { sequence?: string }).sequence
    || (p as { section?: string }).section
    || (p as { channel?: string }).channel;
}

function getPreview(p: AnyPrompt): string | undefined {
  return (p as { previewText?: string }).previewText || (p as { previewSubject?: string }).previewSubject;
}

// ── Main Component ──────────────────────────────────────────────────────

export default function PromptKitPanel({ promptKit, businessContext, campaignId, autoGenerated, onVariationSaved }: Props) {
  const [mode, setMode] = useState<ViewMode>("recommended");
  const [browseCategory, setBrowseCategory] = useState<PromptCategory>("adCopy");
  const [generating, setGenerating] = useState<Set<string>>(new Set());
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [autoStarted, setAutoStarted] = useState(false);
  const [autoProgress, setAutoProgress] = useState(0);
  const mountedRef = useRef(true);

  // Seed results from server-side auto-generated assets (instant on load)
  const [results, setResults] = useState<Record<string, GenerationResult>>(() => {
    const seeded: Record<string, GenerationResult> = {};
    if (autoGenerated) {
      for (const [pid, val] of Object.entries(autoGenerated)) {
        if (val.content) {
          seeded[pid] = { promptId: pid, content: val.content, type: val.type === "image" ? "image" : "text" };
        }
      }
    }
    return seeded;
  });

  // ── Core generation function ────────────────────────────────────────

  const generateOne = useCallback(async (promptId: string, promptText: string) => {
    if (!mountedRef.current) return;
    setGenerating((prev) => new Set(prev).add(promptId));

    try {
      const isImage = isImagePrompt(promptId);
      const endpoint = isImage ? "/api/ai/generate-image" : "/api/ai/generate-copy";
      const body = isImage
        ? { prompt: promptText, campaignId }
        : { prompt: promptText, campaignId, context: businessContext };

      const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();

      if (!mountedRef.current) return;

      if (isImage && data.ok && data.imageBase64) {
        setResults((prev) => ({
          ...prev,
          [promptId]: { promptId, content: "Image generated", type: "image", imageBase64: data.imageBase64 },
        }));
      } else if (!isImage && data.ok && data.content) {
        setResults((prev) => ({
          ...prev,
          [promptId]: { promptId, content: data.content, type: "text" },
        }));
      }
    } catch {
      // Silent fail — non-blocking
    } finally {
      if (mountedRef.current) {
        setGenerating((prev) => {
          const next = new Set(prev);
          next.delete(promptId);
          return next;
        });
      }
    }
  }, [campaignId, businessContext]);

  // ── Auto-generate recommended assets on mount ───────────────────────

  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; };
  }, []);

  useEffect(() => {
    if (autoStarted) return;
    setAutoStarted(true);

    const allPrompts = getAllPrompts(promptKit);
    const recommended = RECOMMENDED_IDS
      .map((id) => allPrompts.find((p) => (p as { id: string }).id === id))
      .filter(Boolean) as AnyPrompt[];

    // Filter out already-generated (from server-side auto-gen)
    const remaining = recommended.filter((p) => !results[(p as { id: string }).id]);

    if (remaining.length === 0) {
      setAutoProgress(recommended.length);
      return;
    }

    // Generate remaining recommended assets sequentially
    const alreadyDone = recommended.length - remaining.length;
    let idx = 0;
    async function generateNext() {
      if (idx >= remaining.length || !mountedRef.current) return;
      const p = remaining[idx];
      const pid = (p as { id: string }).id;
      const prompt = (p as { prompt: string }).prompt;
      setAutoProgress(alreadyDone + idx + 1);
      await generateOne(pid, prompt);
      idx++;
      generateNext();
    }
    generateNext();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoStarted]);

  // ── Actions ─────────────────────────────────────────────────────────

  const [savedIds, setSavedIds] = useState<Set<string>>(new Set());

  async function saveAsVariation(promptId: string, label: string, content: string, isImage: boolean) {
    try {
      const variationContent = isImage
        ? { format: label, hook: `[Image: ${label}]`, imageBase64: content }
        : { format: label, hook: content };
      await fetch(`/api/campaigns/${campaignId}/variations`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: label,
          type: "hook",
          content: variationContent,
          platform: label.includes("TikTok") ? "TikTok" : label.includes("Google") ? "Google" : label.includes("Instagram") ? "Instagram" : "Facebook",
        }),
      });
      setSavedIds((prev) => new Set(prev).add(promptId));
      onVariationSaved?.();
    } catch {
      // Silent
    }
  }

  function copyToClipboard(text: string, id: string) {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  }

  // ── Computed ────────────────────────────────────────────────────────

  const allPrompts = getAllPrompts(promptKit);
  const totalPrompts = allPrompts.length;
  const generatedCount = Object.keys(results).length;
  const recommendedPrompts = RECOMMENDED_IDS
    .map((id) => allPrompts.find((p) => (p as { id: string }).id === id))
    .filter(Boolean) as AnyPrompt[];
  const recommendedDone = recommendedPrompts.filter((p) => results[(p as { id: string }).id]).length;

  // ── Render ─────────────────────────────────────────────────────────

  return (
    <div className="space-y-5">

      {/* ═══ Header ═══ */}
      <div>
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-white">AI Generator</h2>
          <div className="flex items-center gap-2">
            <span className="text-xs text-white/20">{generatedCount}/{totalPrompts} generated</span>
          </div>
        </div>
        <p className="text-xs text-white/40 mt-1">
          Built for <span className="text-cyan-400/70">{businessContext.niche}</span> targeting <span className="text-cyan-400/70">{businessContext.audience}</span>.
          We auto-generate your highest-impact assets first.
        </p>
      </div>

      {/* ═══ Mode Toggle ═══ */}
      <div className="flex gap-2">
        <button
          onClick={() => setMode("recommended")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition border ${
            mode === "recommended"
              ? "border-cyan-500/40 bg-cyan-500/10 text-cyan-300"
              : "border-white/10 bg-white/[0.03] text-white/40 hover:border-white/20"
          }`}
        >
          Recommended
          {recommendedDone < recommendedPrompts.length && (
            <span className="text-[10px] text-cyan-400/50">{recommendedDone}/{recommendedPrompts.length}</span>
          )}
          {recommendedDone === recommendedPrompts.length && recommendedPrompts.length > 0 && (
            <span className="text-[10px] text-green-400">Done</span>
          )}
        </button>
        <button
          onClick={() => setMode("browse")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition border ${
            mode === "browse"
              ? "border-cyan-500/40 bg-cyan-500/10 text-cyan-300"
              : "border-white/10 bg-white/[0.03] text-white/40 hover:border-white/20"
          }`}
        >
          Browse All
          <span className="text-[10px] text-white/20">{totalPrompts}</span>
        </button>
      </div>

      {/* ═══ Auto-Generation Progress Banner ═══ */}
      {mode === "recommended" && generating.size > 0 && (
        <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/[0.06] px-4 py-3 flex items-center gap-3">
          <div className="animate-spin text-cyan-400 text-sm">&#10227;</div>
          <div className="flex-1">
            <p className="text-xs font-semibold text-cyan-300">Auto-generating your top assets...</p>
            <p className="text-[10px] text-cyan-200/50 mt-0.5">{autoProgress} of {recommendedPrompts.length} — sit back, we&apos;re building your campaign</p>
          </div>
          <div className="w-24 h-1.5 rounded-full bg-cyan-900/40 overflow-hidden">
            <div
              className="h-full bg-cyan-400 rounded-full transition-all duration-700"
              style={{ width: `${(recommendedDone / Math.max(recommendedPrompts.length, 1)) * 100}%` }}
            />
          </div>
        </div>
      )}

      {/* ═══ Recommended View ═══ */}
      {mode === "recommended" && (
        <div className="space-y-3">
          {recommendedPrompts.map((p) => {
            const pid = (p as { id: string }).id;
            const label = (p as { label: string }).label;
            const prompt = (p as { prompt: string }).prompt;
            const result = results[pid];
            const isGen = generating.has(pid);
            const badge = getBadge(p);
            const preview = getPreview(p);
            const isImage = isImagePrompt(pid);

            return (
              <PromptCard
                key={pid}
                promptId={pid}
                label={label}
                badge={badge}
                preview={preview}
                promptText={prompt}
                isImage={isImage}
                isGenerating={isGen}
                result={result}
                recommended
                copiedId={copiedId}
                onGenerate={() => generateOne(pid, prompt)}
                onCopy={(text) => copyToClipboard(text, pid)}
                saved={savedIds.has(pid)}
                onSave={(content) => saveAsVariation(pid, label, content, isImage)}
              />
            );
          })}

          {/* Nudge to browse more */}
          {recommendedDone >= 3 && (
            <button
              onClick={() => setMode("browse")}
              className="w-full rounded-2xl border border-dashed border-white/10 hover:border-cyan-400/30 hover:bg-cyan-500/5 py-5 text-sm text-white/30 hover:text-cyan-400 transition"
            >
              Want more? Browse all {totalPrompts} generators →
            </button>
          )}
        </div>
      )}

      {/* ═══ Browse View ═══ */}
      {mode === "browse" && (
        <div className="space-y-4">
          {/* Category pills */}
          <div className="flex flex-wrap gap-2">
            {CATEGORIES.map((cat) => {
              const prompts = getPromptsForCategory(promptKit, cat.id);
              if (prompts.length === 0) return null;
              const doneInCat = prompts.filter((p) => results[(p as { id: string }).id]).length;
              return (
                <button
                  key={cat.id}
                  onClick={() => setBrowseCategory(cat.id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition border ${
                    browseCategory === cat.id
                      ? "border-cyan-500/40 bg-cyan-500/10 text-cyan-300"
                      : "border-white/10 bg-white/[0.03] text-white/40 hover:border-white/20 hover:text-white/60"
                  }`}
                >
                  <span>{cat.icon}</span>
                  <span>{cat.label}</span>
                  {doneInCat > 0 && (
                    <span className="text-[10px] text-green-400">{doneInCat}</span>
                  )}
                </button>
              );
            })}
          </div>

          {/* Prompt cards for selected category */}
          <div className="space-y-3">
            {getPromptsForCategory(promptKit, browseCategory).map((p) => {
              const pid = (p as { id: string }).id;
              const label = (p as { label: string }).label;
              const prompt = (p as { prompt: string }).prompt;
              const result = results[pid];
              const isGen = generating.has(pid);
              const badge = getBadge(p);
              const preview = getPreview(p);
              const isImage = isImagePrompt(pid);

              return (
                <PromptCard
                  key={pid}
                  promptId={pid}
                  label={label}
                  badge={badge}
                  preview={preview}
                  promptText={prompt}
                  isImage={isImage}
                  isGenerating={isGen}
                  result={result}
                  copiedId={copiedId}
                  onGenerate={() => generateOne(pid, prompt)}
                  onCopy={(text) => copyToClipboard(text, pid)}
                  saved={savedIds.has(pid)}
                  onSave={(content) => saveAsVariation(pid, label, content, isImage)}
                />
              );
            })}
          </div>
        </div>
      )}

      {/* ═══ Footer stats ═══ */}
      {generatedCount > 0 && (
        <div className="flex items-center justify-between pt-4 border-t border-white/10">
          <p className="text-xs text-white/20">{generatedCount} assets generated this session</p>
          <button
            onClick={() => {
              const allText = Object.values(results)
                .filter((r) => r.type === "text")
                .map((r) => `## ${r.promptId}\n\n${r.content}`)
                .join("\n\n---\n\n");
              copyToClipboard(allText, "all");
            }}
            className="text-xs text-cyan-400/60 hover:text-cyan-400 transition"
          >
            {copiedId === "all" ? "Copied!" : "Export all text"}
          </button>
        </div>
      )}
    </div>
  );
}

// ── PromptCard ──────────────────────────────────────────────────────────

function PromptCard({
  promptId,
  label,
  badge,
  preview,
  promptText,
  isImage,
  isGenerating,
  result,
  recommended,
  copiedId,
  saved,
  onGenerate,
  onCopy,
  onSave,
}: {
  promptId: string;
  label: string;
  badge?: string;
  preview?: string;
  promptText: string;
  isImage: boolean;
  isGenerating: boolean;
  result?: GenerationResult;
  recommended?: boolean;
  saved?: boolean;
  copiedId: string | null;
  onGenerate: () => void;
  onCopy: (text: string) => void;
  onSave?: (content: string) => void;
}) {
  return (
    <div
      className={`rounded-2xl border overflow-hidden transition-all ${
        result
          ? "border-green-500/20 bg-green-500/[0.03]"
          : isGenerating
            ? "border-cyan-500/20 bg-cyan-500/[0.03]"
            : "border-white/10 bg-white/[0.03] hover:border-cyan-400/20"
      }`}
    >
      {/* Header */}
      <div className="p-4">
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap mb-1">
              {recommended && !result && !isGenerating && (
                <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded bg-amber-500/15 text-amber-400 border border-amber-500/20">
                  Recommended
                </span>
              )}
              {badge && (
                <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded bg-cyan-500/15 text-cyan-400 border border-cyan-500/20">
                  {badge}
                </span>
              )}
              {result && (
                <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-green-500/15 text-green-400 border border-green-500/20">
                  Ready
                </span>
              )}
              {isGenerating && (
                <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-cyan-500/15 text-cyan-300 border border-cyan-500/20 animate-pulse">
                  Generating...
                </span>
              )}
            </div>
            <h3 className="text-sm font-bold text-white">{label}</h3>
            {preview && !result && !isGenerating && (
              <p className="text-xs text-white/40 mt-1 italic leading-relaxed">{preview}</p>
            )}
          </div>

          {/* Action button */}
          {!isGenerating && (
            <button
              onClick={onGenerate}
              className={`shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-black uppercase tracking-wide transition ${
                result
                  ? "bg-white/5 text-white/40 hover:bg-white/10 border border-white/10"
                  : "bg-cyan-500 text-[#0a0f1e] hover:bg-cyan-400 shadow-[0_0_20px_rgba(6,182,212,0.25)]"
              }`}
            >
              {result ? "Redo" : "Generate"}
            </button>
          )}
          {isGenerating && (
            <div className="shrink-0 px-4 py-2">
              <div className="w-5 h-5 border-2 border-cyan-400 border-t-transparent rounded-full animate-spin" />
            </div>
          )}
        </div>

        {/* View prompt toggle (only in browse mode, not when result shown) */}
        {!result && !isGenerating && !recommended && (
          <details className="mt-3">
            <summary className="text-[10px] text-white/20 cursor-pointer hover:text-white/40 transition">
              View prompt
            </summary>
            <pre className="mt-2 p-3 rounded-lg bg-black/30 text-[10px] text-white/30 leading-relaxed whitespace-pre-wrap font-mono max-h-32 overflow-y-auto">
              {promptText}
            </pre>
          </details>
        )}
      </div>

      {/* ── Result Display ── */}
      {result && (
        <div className="border-t border-white/10 p-4 bg-black/20">
          {result.type === "image" && result.imageBase64 ? (
            <div className="space-y-3">
              <img
                src={`data:image/png;base64,${result.imageBase64}`}
                alt={label}
                className="rounded-xl max-w-full max-h-72 mx-auto shadow-[0_8px_32px_rgba(0,0,0,0.4)]"
              />
              <div className="flex gap-2">
                <a
                  href={`data:image/png;base64,${result.imageBase64}`}
                  download={`${promptId}.png`}
                  className="flex-1 text-center px-3 py-2 rounded-lg bg-cyan-500 text-[#0a0f1e] text-xs font-bold hover:bg-cyan-400 transition"
                >
                  Download
                </a>
                <button
                  onClick={() => onCopy(result.imageBase64!)}
                  className="px-3 py-2 rounded-lg border border-white/10 bg-white/5 text-white/40 text-xs hover:text-white/60 transition"
                >
                  {copiedId === promptId ? "Copied!" : "Copy"}
                </button>
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="max-h-60 overflow-y-auto">
                <pre className="whitespace-pre-wrap text-sm text-white/80 leading-relaxed font-sans">
                  {result.content}
                </pre>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => onCopy(result.content)}
                  className="flex-1 text-center px-3 py-2 rounded-lg bg-cyan-500 text-[#0a0f1e] text-xs font-bold hover:bg-cyan-400 transition"
                >
                  {copiedId === promptId ? "Copied!" : "Copy"}
                </button>
                {onSave && (
                  <button
                    onClick={() => onSave(result.content)}
                    disabled={saved}
                    className={`px-3 py-2 rounded-lg text-xs font-bold transition ${
                      saved
                        ? "bg-green-500/10 border border-green-500/20 text-green-400"
                        : "bg-white/5 border border-white/10 text-white/40 hover:text-white/70 hover:bg-white/10"
                    }`}
                  >
                    {saved ? "Saved" : "Save to Campaign"}
                  </button>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
