// ---------------------------------------------------------------------------
// POST /api/invoices/generate
// Generates a professional invoice from client + package data
// Returns markdown invoice that can be exported to PDF
// ---------------------------------------------------------------------------

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { getOrCreateUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function POST(req: NextRequest) {
  try {
    const { userId: clerkId } = await auth();
    if (!clerkId) return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    const user = await getOrCreateUser();
    if (!user) return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });

    const body = await req.json() as {
      clientName: string;
      clientEmail?: string;
      items: { description: string; amount: number }[];
      dueDate?: string;
      notes?: string;
    };

    if (!body.clientName || !body.items?.length) {
      return NextResponse.json({ ok: false, error: "clientName and items required" }, { status: 400 });
    }

    // Load business profile for invoice header
    const profile = await prisma.businessProfile.findUnique({ where: { userId: user.id } });
    const dbUser = await prisma.user.findUnique({
      where: { id: user.id },
      select: { name: true, email: true, workspaceName: true },
    });

    const businessName = profile?.businessName ?? dbUser?.workspaceName ?? "Himalaya Business";
    const total = body.items.reduce((s, i) => s + i.amount, 0);
    const invoiceNumber = `INV-${Date.now().toString(36).toUpperCase()}`;
    const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const dueDate = body.dueDate ?? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

    const invoice = `# INVOICE

**${businessName}**
${dbUser?.email ?? ""}

---

**Invoice #:** ${invoiceNumber}
**Date:** ${today}
**Due Date:** ${dueDate}

---

**Bill To:**
${body.clientName}
${body.clientEmail ?? ""}

---

## Items

| Description | Amount |
|-------------|--------|
${body.items.map((i) => `| ${i.description} | $${i.amount.toFixed(2)} |`).join("\n")}
| **Total** | **$${total.toFixed(2)}** |

---

${body.notes ? `## Notes\n\n${body.notes}\n\n---\n\n` : ""}## Payment Terms

- Payment is due within 30 days of invoice date
- Accepted methods: bank transfer, credit card, or Stripe payment link
- Late payments may incur a 1.5% monthly fee

---

*Generated by Himalaya Marketing OS*`;

    return NextResponse.json({
      ok: true,
      invoice,
      invoiceNumber,
      total,
      dueDate,
    });
  } catch (err) {
    console.error("Invoice error:", err);
    return NextResponse.json({ ok: false, error: "Failed" }, { status: 500 });
  }
}
